### ISSUE TITLE
Random Label Identifiers

### ISSUE THREAD

**Issue by gthomsen** [scalabel/scalabel#151]
**Problem**
It appears that label identifiers are random which prevents association between frames in a video.  

**To Reproduce**
1. Pull the `a43fb425e101` scalabel/www image (created 020-06-13T00:47:50)
2. Create a new project with Video items and 2D Bounding Boxes as labels
3. Create a label on the first frame.  Save the annotations.
4. Visit the project's dashboard and export the results
5. Open the exported .json and look at each frame's label's "id" attribute - each is random

```shell
$ grep '"id"' ~/Downloads/bug-report_export_2020-06-14_18-18-13.json 
        "id": "twJJyynf78gR96po",
        "id": "SvNsr5YKT0PxvVJA",
        "id": "6TEINnZOIhV0yNmS",
        "id": "uLnnNulC99sEMERD",
        "id": "bWZGJ8J53ILpbalt",
        "id": "7makKyXa2lCcSc0R",
        "id": "cFugoRnoFxEnnTop",
        "id": "HaX2iKXCOtXZUKrZ",
        "id": "yeVvm5K7b1dts6Ma",
        "id": "2CPYavWawimOK8D7",
        "id": "ibFKGIxhQ7KbRjGY",
        "id": "inczLmSuskfpkwqX",
        "id": "Y7oViWgDQzl72ZVD",
        "id": "ZjXl4B4PejX7Yme1",
        "id": "OPA3ah6YeuxTLQ5o",
        "id": "LJV9wGZ1hGkU9IdN",
        "id": "bu4IFbgrpXBGXVCn",
        "id": "Cf756phcILJVJzd5",
        "id": "lra93q1cNSxRpidL",
        "id": "1fJyGCt4zCzwmMqe",
```

**Expected behavior**
I would expect the label's identifier to remain constant throughout all of the video frames.

**Comment by fyu** [comment]
Are you trying to do tracking annotation? If you select tracking mode, the same object on different frames will always have the same ID.

**Comment by gthomsen** [comment]
How do I select tracking mode?  

For a new project I specify Item type as Video and Label Type as 2D Bounding Box.  An Item List and Categories are provided, Attributes, Label Specification, and Sensors are not.  During annotation, I click "Track-Link", create a bounding box, and move/adjust it between successive frames.  When done with one instance I click "Finish Track-Link", save and submit.  There are N-many unique identifiers, one per each of the N frames.

**Comment by fyu** [comment]
Currently, when you set the item type as video, you are in tracking mode. #158 shall fix the problem you see. You can simply update the built code and export the labels again.

By the way, if you want to track an object, you don't need "Track-Link". It is used to link two existing tracks. Say you have two tracklets, one from Frame 1 to 5 and the other from Frame 9 to 10. The tracklets may represent the same object but it is occluded from Frame 6 to 8. In this case, you can use "Track-Link" to link the two tracklets so that in exported file, the boxes in those tracklets will have the same ID.
