### ISSUE TITLE
Video Tracking memory leak

### ISSUE THREAD

**Issue by alemelis** [scalabel/scalabel#220]
**Describe the bug**
When in `video tracking` mode, RAM usage ramps up quickly as few boxes are added. The browser freezes after few seconds as all the memory fills up. I have 600 images in the set I'm trying to label.

**Desktop:**
 - OS: Ubuntu
 - Browser: Firefox 79.0

**Additional context**
I'm using the docker image to spin up the service

**Comment by fyu** [comment]
This is strange. It is probably because you have too many images for your browser and memory. I have tested the tracking mode with the attached 1000-image list. It took a while to load all the images, but I could create and edit tens of tracks without lagging. The task manager said most of the memory was taken by the images. I tried both Chrome and Firefox on Mac. Try the attached list and see whether you still see the problem?

[dancing_images.yml.zip](https://github.com/scalabel/scalabel/files/5128145/dancing_images.yml.zip)

**Comment by alemelis** [comment]
@fyu thanks for the reply

Indeed, the images you linked work fine and the RAM is not filled up.

I'm now trying to upload my images to a S3 bucket. I set all the permissions to public but scalabel is not able to load them (I get the `Failed to load image at https://s3...` message). Is there any particular config/permission I should set on aws?

**Comment by fyu** [comment]
It is likely because the image access is blocked by CORS setting for the bucket. You can find more information about s3 bucket CORS setting here: https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-cors-configuration.html.

For example, if you want to allow cross domain image access from anywhere, you can use the CORS configuration below
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
</CORSRule>
</CORSConfiguration>
```

**Comment by fyu** [comment]
For the images, you can try to use our `prepare_data` tool to break the videos into images: https://github.com/scalabel/scalabel/tree/master/scalabel/tools. The result images will have a similar format as my examples. I have tested Scalabel up to 2000 images in one tracking task and it works well.

**Comment by alemelis** [comment]
Thanks @fyu, it was the missing CORS setting!
